exQueryStudio/grails-app/controllers/exquery/HomePageController.groovy
package exquery

import exquery.util.CommonUtil
import org.apache.log4j.Logger

import jofc2.model.elements.PieChart
import jofc2.model.Chart
import jofc2.model.elements.PieChart.Slice
import exquery.valuebeans.export.TaxonomyDivisionVO
import exquery.common.TaxDivisionUtil
import jofc2.model.elements.Tooltip
import exquery.common.OrganUtil
import exquery.common.SpeciesUtil
import exquery.common.ProjectInitMap;


class HomePageController {

    Logger gLogger = Logger.getLogger(HomePageController.class)

    def speciesService
  
    def index = {
      gLogger.info  'comming into init method of HomePageController'


      def PrototypeInfo = ["experimentSize":ProjectInitMap.getInstance().get("EXPERIMENT_COUNT"),"classesSize":ProjectInitMap.getInstance().get("CLASSES_COUNT"),"samplesSize":ProjectInitMap.getInstance().get("SAMPLES_COUNT")]

      println PrototypeInfo

      //session.setAttribute("PrototypeInfo", PrototypeInfo);

      /* Remove session varibles*/
      if(session.getAttribute("resultData")!=null){
        session.removeAttribute("resultData")
      }
      if(session.getAttribute("txtIds")!=null){
        session.removeAttribute("txtIds")
      }
      
      if(session.getAttribute("APPS_UPDATE_DATE")!=null){
        session.removeAttribute("APPS_UPDATE_DATE")
      }

      def sxObjectType = CommonUtil.getInstance().getSXObjectType();
      def getSXSearchObjectType = CommonUtil.getInstance().getSXSearchObjectType();

      //Added by pradeep on 6th April - Provide top organs and species list on home page :Start
      def sxOrgansList = OrganUtil.getInstance().getUniqueSxOrgans()
      def sxSpeciesList = SpeciesUtil.getInstance().getUniqueSxSpecies()
      //Added by pradeep on 6th April - Provide top organs and species list on home page :End
      gLogger.info  'out from init method of HomePageController'
      return [PrototypeInfo:PrototypeInfo,sxObjectType:sxObjectType,getSXSearchObjectType:getSXSearchObjectType,sxOrgansList:sxOrgansList,sxSpeciesList:sxSpeciesList]
    }

    /**
     * Prepare Species chart data
     */
    def SPECIES_PIE_CHART = {
            def pieChart = new PieChart()
            pieChart.setAnimate(true)
            pieChart.setStartAngle(35)
            pieChart.setBorder(2)
            pieChart.setAlpha(0.8f)
            //def uniqueDivisions = speciesService.getUniqueDivisions()

            def uniqueDivisions = TaxDivisionUtil.getInstance().getUniqueDivisions()

            if(uniqueDivisions!=null && uniqueDivisions.size()>0){
                Slice slice
                String strToolTip
                uniqueDivisions.each {TaxonomyDivisionVO taxonomyDivisionVO->
                    slice = new Slice(taxonomyDivisionVO?.samplesCount,"${taxonomyDivisionVO?.divisionName} [${taxonomyDivisionVO?.samplesCount}]")

                    strToolTip  = "Brief Details<br>Experiment Count: ${taxonomyDivisionVO?.experimentCount}"
                    strToolTip += "<br>Classes Count: ${taxonomyDivisionVO?.classesCount}"
                    strToolTip += "<br>Species Name: "//${taxonomyDivisionVO?.speciesName.toString().replaceAll(";",";<br>                      ")}"

                    def speciesNames = taxonomyDivisionVO?.speciesName.toString().split("; ")
                    //println speciesNames
                    if(speciesNames!=null && speciesNames.length>0){
                        for(int index=0; index<speciesNames.length; index++){
                            if(index<10){
                                if(index==0){
                                    strToolTip += "${speciesNames[index]}"
                                }else{
                                    strToolTip += ";<br>                      ${speciesNames[index]}"
                                }
                            }else{
                                strToolTip += ";<br>                       more..."
                                break;
                            }
                        }
                    }

                    slice.setTip(strToolTip)
                    pieChart.addSlices(slice)
                    pieChart.setColours("#${getNewColor()}")
                }

            }

            //pieChart.setTooltip("#val# of #total#<br>#percent# of 100%")

            Chart c = new Chart("Divisions of Species and Samples Count").addElements(pieChart)

            //c.setBackgroundColour("#E0ECF8") //to change graph's Background Colour
            Tooltip tip = new Tooltip()
            tip.setBackgroundColour("#E0ECF8")
            tip.setColour("#E0ECF8")
            c.setTooltip(tip)

            render c.toString()
    }


    private colorList = []
    //Random generator = new Random((new Date()).getDate());
    Random generator = new Random(4238423);
    /**
     * Generate Random Color Code
     * @return
     */
    private int getNewColor(){

        int code = generator.nextInt(999999) + 1

        if(colorList!=null && !colorList.contains(code)){
          colorList.add(code)
          //println colorList
          return code
        }else{
          code = getNewColor()
          if(code==-1){
            code = getNewColor()
          }
        }
        return -1
    }



}

exQueryStudio/grails-app/controllers/exquery/SpeciesController.groovy
package exquery

import org.apache.log4j.Logger
import exquery.valuebeans.export.SpeciesVO
import exquery.util.FormatResultUtil
import org.codehaus.groovy.grails.commons.ConfigurationHolder
import exquery.util.ExportExperimentUtil

class SpeciesController {
    Logger gLogger = Logger.getLogger(SpeciesController.class)
    def speciesService
    def classSampleService
    def experimentClassService
    def experimentService
    def exportService
    def searchService

    FormatResultUtil formatResultUtil = new FormatResultUtil()

    def index = {
        redirect( controller:"search" ,params:[cmbSearchBy:"Species",searchText:"*"],action:"search")
    }

    def datalist={
      gLogger.info 'coming into action:datalist of controller:species'
      gLogger.info "params :: ${params}"
      def speciesName = params.speciesName
      def lookupBy = params.lookupBy
      def title="Result List By Species"
      def isExport = false
      if(params?.format && params.format != "html"){
        isExport = true
      }
      SpeciesVO speciesVO = speciesService.getSXSpeciesBySpeciesName(speciesName)
      def resultData = null

        if(lookupBy!=null && lookupBy.toString().trim().equalsIgnoreCase("experiments")){
             title="Experiment List By Species '${speciesName}'"
             def classIds = speciesService.getClassIdsBySpeciesName(speciesName)
             def result = experimentService.getExperimentsByClassIds(classIds)
             resultData = FormatResultUtil.getInstance().prepareExperimentsResult(result,params,isExport)

             if( result == null || result.size()==0 ){
                resultData.putAt "ErrorMsg","No Recoed Found"
             }else{
                resultData?.putAt "TotalRecordCount",result.size()
                resultData?.putAt "isExport",true
             }

          }else if(lookupBy!=null && lookupBy.toString().trim().equalsIgnoreCase("classes")){
             title="Class List By Species '${speciesName}'"
             def classIds = speciesService.getClassIdsBySpeciesName(speciesName)
             def result = experimentClassService.getClassesByClassIds(classIds)
             resultData = FormatResultUtil.getInstance().prepareClassesResult(result,params,isExport)

             if( result == null || result.size()==0 ){
                resultData.putAt "ErrorMsg","No Recoed Found"
             }else{
                resultData?.putAt "TotalRecordCount",result.size()
                resultData?.putAt "isExport",true
             }


          }else if(lookupBy!=null && lookupBy.toString().trim().equalsIgnoreCase("samples")){
             title="Sample List By Species '${speciesName}'"
             def samplesIds = speciesService.getSampleIdsBySpeciesName(speciesName)
             def result = classSampleService.getSamplesBySamplesIds(samplesIds)


             resultData = FormatResultUtil.getInstance().prepareSamplesResult(result,params,isExport)

             if( result == null || result.size()==0 ){
                resultData.putAt "ErrorMsg","No Recoed Found"
             }else{
                resultData?.putAt "TotalRecordCount",result.size()
                resultData?.putAt "isExport",true
             }
          }

        // Export Result
        if(params?.format && params.format != "html"){
          response.contentType = ConfigurationHolder.config.grails.mime.types[params.format]
          response.setHeader("Content-disposition", "attachment; filename=${lookupBy}LookUpBySpeciesResult.${params.extension}")
          if(resultData?.parameters?.title!=null){
            resultData?.parameters?.title = title
          }
          exportService.export(params.format, response.outputStream, resultData.resultList, resultData.fieldList, resultData.labelMap, resultData.formatters, resultData.parameters)
        }

      gLogger.info 'out from action:datalist of controller:species'
      return ["speciesName":speciesName,"lookupBy":lookupBy,"title":title,"speciesInfo":speciesVO,"result": resultData]
    }

    def exportexp={
      gLogger.info 'coming into action:exportexp of controller:species'
      gLogger.info "params :: ${params}"
      def speciesName = params.speciesName

      def classIds = speciesService.getClassIdsBySpeciesName(speciesName)
      def result = experimentService.getExperimentsByClassIds(classIds)
      gLogger.info "result :: ${result}"

      def workBook = ExportExperimentUtil.getInstance().exportExperiment(result)
      gLogger.info "workBook :: ${workBook}"

      // Export Result
      if(params?.format && params.format != "html"){
        String fileName = speciesName.toString().replace(" ","_")

        response.contentType = ConfigurationHolder.config.grails.mime.types[params.format]
        response.setHeader("Content-disposition", "attachment; filename=ExperimentsWithSpecies_${fileName}.${params.extension}")

        File temp = File.createTempFile("${speciesName}", ".${params.extension}");
        temp.deleteOnExit();

        // The Output file is where the xls will be created
        FileOutputStream fOut = new FileOutputStream(temp);
        // Write the XL sheet
        workBook.write(fOut);
        fOut.flush();
        // Done Deal..
        fOut.close();

        response.outputStream << temp.getBytes()
        response.outputStream.flush()
      }
      gLogger.info 'out from action:exportexp of controller:species'
      return
    }

    def list={
      //set lookup params
      params.put("cmbSearchBy","Species")
      params.put("searchText","*")


      def searchBy = params.cmbSearchBy
      def searchText = params.searchText

      // Export Result
      def resultData = []
      if(params?.format && params.format != "html"){
          response.contentType = ConfigurationHolder.config.grails.mime.types[params.format]
          response.setHeader("Content-disposition", "attachment; filename=${searchBy}List.${params.extension}")
          resultData = processSearch(searchBy,searchText,params,true)

          if(resultData?.parameters?.title!=null){
              resultData?.parameters?.title = "Species List"
          }

          exportService.export(params.format, response.outputStream, resultData.resultList, resultData.fieldList, resultData.labelMap, resultData.formatters, resultData.parameters)
      }else{

          resultData = processSearch(searchBy,searchText,params)
    }


    return [result: resultData]
  }


  private def processSearch(def searchBy,def searchText, def params = [:],boolean isExport = false){
    //call the service to search the data
      def resultSearch = searchService.search(searchBy, searchText, params)

      Collection<Map<?, ?>> result = resultSearch?.result
      def resultData = null
      resultData = FormatResultUtil.getInstance()."prepare${searchBy}Result"(result,params,isExport)

      if( resultSearch?.ErrorMsg != null ){
        resultData.putAt "ErrorMsg",resultSearch?.ErrorMsg
      }

      resultData?.putAt "isPaginate",resultSearch?.isPaginate
      resultData?.putAt "TotalRecordCount",resultSearch?.TotalRecordCount
      resultData?.putAt "isExport",resultSearch?.isExport

      return resultData
  }

}

exQueryStudio/grails-app/views/species/_speciesList.gsp
<%--
  Created by IntelliJ IDEA.
  User: pradeep
  Date: 5/6/11
  Time: 12:38 PM
  To change this template use File | Settings | File Templates.
--%>

<div>
    <g:if test="${sxSpeciesList!=null && sxSpeciesList?.size()>0}">

        <%
            int maxCount=10
            def species
            for(int index=0; index < sxSpeciesList.size() && index < maxCount; index++){
                species = sxSpeciesList.get(index)

        %>
        %{--<g:each in="${sxSpeciesList}" var="species" status="index">--}%

            <g:if test="${index==0}">
                <span style="cursor:pointer;" title="ExperimentCount:${species.experimentCount}, ClassesCount:${species.classesCount} and SamplesCount:${species.samplesCount}">${species.speciesName}[${species.samplesCount}]</span>
            </g:if>
            <g:else>
                ;&nbsp;&nbsp;<span style="cursor:pointer;" title="ExperimentCount:${species.experimentCount}, ClassesCount:${species.classesCount} and SamplesCount:${species.samplesCount}">${species.speciesName}[${species.samplesCount}]</span>
            </g:else>
        %{--</g:each>--}%
        <%
            }
        %>
        <g:if test="${sxSpeciesList.size()>maxCount}">
             <span style="cursor:pointer;" > <g:link controller="species" action="list" title="click to get the list of species">more...</g:link> </span>
        </g:if>
    </g:if>
    <g:else>
       <div class="errors">
        No Species
       </div>
    </g:else>
</div>

exQueryStudio/grails-app/views/species/datalist.gsp
<%@ page import="exquery.util.CommonUtil" contentType="text/html;charset=UTF-8" %>


<html>
<head>
  <meta name="layout" content="main"/>
  <export:resource />
</head>

<body>
<div id="container">
       <div id="header">
            <g:render template="../templates/header"/>
       </div>

      <div id="main">
        <div class="box">
            <div class="nav">
            <span class="menuButton"><g:link controller="homePage" action="index" class="home">Home</g:link></span>
            <span class="menuButton"><a href="javascript://nop" class="back" onclick="history.back(1)">Back to result</a></span>
         </div>

          <div class="appsHeader"> ${title} </div>

          <div class='info_header' style="vertical-align:bottom">
            <span class="info_title">&nbsp;Species</span>
          </div>
          <div class="info">
              <table width="100%" cellpadding="0" cellspacing="0" class="table_noborder">
                  <tr>
                    <td width="10%" class="forminputlabel"> <g:message code="SXspecies.ncbiId"/></td>
                    <td width="1%"> : </td>
                    <td width="30%"><a href="http://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?mode=Info&id=${speciesInfo?.ncbiId}&lvl=3&lin=f&keep=1&srchmode=1&unlock" target="_blank" title="Click to get more info">NCBI: ${speciesInfo?.ncbiId}</a></td>
                    <td width="1%">&nbsp;</td>
                    <td width="10%" class="forminputlabel"><g:message code="SXspecies.scientificName"/> </td>
                    <td width="1%"> : </td>
                    <td width="30%">${speciesInfo?.scientificName}</td>

                  </tr>
                  <tr>
                    <td width="10%" class="forminputlabel"> <g:message code="SXspecies.organs"/> </td>
                    <td width="1%"> : </td>
                    <td width="30%">${CommonUtil.getInstance().convertNameListIntoString(speciesInfo?.organs)}</td>
                    <td width="1%">&nbsp;</td>
                    <td width="10%" class="forminputlabel"> <g:message code="SXspecies.synonyms"/></td>
                    <td width="1%"> : </td>
                    <td width="30%">${CommonUtil.getInstance().convertNameListIntoString(speciesInfo?.synonyms)}</td>
                  </tr>

                  <g:if test='${lookupBy?.toString().trim().equalsIgnoreCase("experiments")}'>
                  <tr>
                    <td width="10%" class="forminputlabel"> <g:message code="SXspecies.classesCount"/></td>
                    <td width="1%"> : </td>
                    <td width="30%"><g:link controller="species" action="datalist" params='[lookupBy:"classes",speciesName:"${speciesName}"]'>${speciesInfo?.classesCount}</g:link></td>
                    <td width="1%">&nbsp;</td>
                    <td width="10%" class="forminputlabel"> <g:message code="SXspecies.samplesCount"/></td>
                    <td width="1%"> : </td>
                    <td width="30%"><g:link controller="species" action="datalist" params='[lookupBy:"samples",speciesName:"${speciesName}"]'>${speciesInfo?.samplesCount}</g:link></td>
                  </tr>
                   </g:if>
                  <g:if test='${lookupBy?.toString().trim().equalsIgnoreCase("classes")}'>

                  <tr>
                    <td width="10%" class="forminputlabel"> <g:message code="SXspecies.experimentCount"/></td>
                    <td width="1%"> : </td>
                    <td width="30%"><g:link controller="species" action="datalist" params='[lookupBy:"experiments",speciesName:"${speciesName}"]'>${speciesInfo?.experimentCount}</g:link></td>
                    <td width="1%">&nbsp;</td>
                    <td width="10%" class="forminputlabel"> <g:message code="SXspecies.samplesCount"/></td>
                    <td width="1%"> : </td>
                    <td width="30%"><g:link controller="species" action="datalist" params='[lookupBy:"samples",speciesName:"${speciesName}"]'>${speciesInfo?.samplesCount}</g:link></td>
                  </tr>
                  </g:if>

                  <g:if test='${lookupBy?.toString().trim().equalsIgnoreCase("samples")}'>
                  <tr>
                    <td width="10%" class="forminputlabel"> <g:message code="SXspecies.experimentCount"/></td>
                    <td width="1%"> : </td>
                    <td width="30%"><g:link controller="species" action="datalist" params='[lookupBy:"experiments",speciesName:"${speciesName}"]'>${speciesInfo?.experimentCount}</g:link></td>
                    <td width="1%">&nbsp;</td>
                    <td width="10%" class="forminputlabel"> <g:message code="SXspecies.classesCount"/></td>
                    <td width="1%"> : </td>
                    <td width="30%"><g:link controller="species" action="datalist" params='[lookupBy:"classes",speciesName:"${speciesName}"]'>${speciesInfo?.classesCount}</g:link></td>
                  </tr>
                  </g:if>
              </table>
          </div>

          <div class='info_header' style="vertical-align:bottom">
            <span class="info_title">&nbsp;Result List</span>
          </div>
          <div class="info">
              <table class="result">

                <%
                  if (result.fieldList != null && result.fieldList.size() > 0) {
                %>
               <tr>
                <g:each var="headerField" in="${result.fieldList}">
                <%
                      def cssClass = result.cssClassMap.get(headerField)
                      def header = result.labelMap.get(headerField)
                %>
                  <th class="${cssClass}">${header}</th>

                  %{--<g:sortableColumn property="${headerField}" title="${header}" params="[cmbSearchBy: params.cmbSearchBy,searchText:params.searchText]" />--}%

                </g:each>
                </tr>

                <%
                  }  %>

                <%
                  if (result.resultList != null && result.resultList.size() > 0) {
                    long rowNo=1;
                %>
                   <g:each var="row" in="${result.resultList}" status="index">
                   <%
                      String lStrClass = "";

                      if (index % 2 == 0) {
                        lStrClass = "even"
                      } else {
                        lStrClass = "odd"
                      }
                  %>

                  <tr class='<%=lStrClass%>' onMouseOver="this.className='highlight'" onMouseOut="this.className='<%=lStrClass%>'" >

                    <g:each var="columnfield" in="${result.fieldList}">
                    <%
                          cssClass = result.cssClassMap.get(columnfield)
                          def data = row.get(columnfield)
                    %>
                    <td class="${cssClass}">${data}</td>
                    </g:each>
                  </tr>
                </g:each>

                <%
                  } else {
                %>
                <tr>
                  <td colspan="${result.fieldList?.size}" class='even'>
                    <div class="errors">

                      ${result?.ErrorMsg}

                    </div>
                  </td>

                </tr>
                <% }
                %>
              </table>

              <g:if test="${result?.TotalRecordCount != null}">
                  <div class="pagination_top">
                   <g:customPaginate isPaginate="false" total="${result?.TotalRecordCount}" />
                  </div>

                  <g:if test="${result?.isExport != null && result?.isExport}" >
                      <export:formats formats="['csv', 'excel', 'pdf', 'rtf']" params="[lookupBy: lookupBy,speciesName:speciesName]" />
                  </g:if>
              </g:if>

          </div>

     </div>
     <!-- End div box -->
     <div class="groupbox">
       <g:render template="../templates/blank"/>
     </div>


     </div>
     <!-- End div main -->
     <div id="footer">
       <g:render template="../templates/footer"/>
     </div>
</div>
</body>

</html>

exQueryStudio/grails-app/views/species/list.gsp
<%--
  Created by IntelliJ IDEA.
  User: pradeep
  Date: 5/6/11
  Time: 1:17 PM
  To change this template use File | Settings | File Templates.
--%>

<html>
<head>
  <meta name="layout" content="main"/>
  <export:resource />
</head>

<body id="search">
<div id="container">
       <div id="header">
            <g:render template="../templates/header"/>
       </div>
      <!-- Start div main -->
      <div id="main">
        <div class="box">

          %{--<div id="pagePath">--}%
            %{--<h1><g:link controller="homePage" action="index" class="home">Home</g:link> <span>&raquo;</span> <g:link controller="search" params="[cmbSearchBy: params.cmbSearchBy,searchText:params.searchText]" action="index" class="search">Search</g:link> <span>&raquo;</span> <a class="searchresult"> Search Result </a> </h1>--}%
          %{--</div>--}%

          <div class="nav">
            <span class="menuButton"><g:link controller="homePage" action="index" class="home" >Home</g:link></span>
          </div>

          <div class="appsHeader"> Species List </div>

      <div class='info_header' style="vertical-align:bottom">
        <span class="info_title">&nbsp;List</span>
      </div>
      <div class="info">

      <table class="result">

        <%
          if (result.fieldList != null && result.fieldList.size() > 0) {
        %>
       <tr>
        <g:each var="headerField" in="${result.fieldList}">
        <%
              def cssClass = result.cssClassMap.get(headerField)
              def header = result.labelMap.get(headerField)
        %>
          <th class="${cssClass}">${header}</th>

        </g:each>
        </tr>

        <%
          }  %>

        <%
          if (result.resultList != null && result.resultList.size() > 0) {
            long rowNo=1;
        %>
           <g:each var="row" in="${result.resultList}" status="index">
           <%
              String lStrClass = "";

              if (index % 2 == 0) {
                lStrClass = "even"
              } else {
                lStrClass = "odd"
              }
          %>

          <tr class='<%=lStrClass%>' onMouseOver="this.className='highlight'" onMouseOut="this.className='<%=lStrClass%>'" >

            <g:each var="columnfield" in="${result.fieldList}">
            <%
                  cssClass = result.cssClassMap.get(columnfield)
                  def data = row.get(columnfield)
            %>
            <td class="${cssClass}">${data}</td>
            </g:each>
          </tr>
        </g:each>

        <%
          } else {
        %>
        <tr>
          <td colspan="${result.fieldList?.size}" class='even'>
            <div class="errors">

              ${result?.ErrorMsg}

            </div>
          </td>

        </tr>
        <% }
        %>
      </table>


      <%
       if (result.resultList != null && result.resultList.size() > 0) {
            if( result?.isPaginate != null && result?.isPaginate ){
                if(result.resultList != null && result.resultList.size() > 0){
      %>
                  <div class="pagination_bottom">
                    <g:customPaginate  controller="search" action="search" total="${result?.TotalRecordCount}" prev="&lt; previous" next="next &gt;"/>
                  </div>

                  <export:formats formats="['csv', 'excel', 'pdf', 'rtf']" />

      <%        }
            } else {
                if( result?.TotalRecordCount != null ){
     %>
                   <div class="pagination_top">
                    <g:customPaginate isPaginate="false" total="${result?.TotalRecordCount}" />
                   </div>

                   <g:if test="${result?.isExport != null && result?.isExport}" >
                     <export:formats formats="['csv', 'excel', 'pdf', 'rtf']" />
                   </g:if>
     <%          }
             }
        }
     %>

      </div>
      <!-- End div info : result -->
    </div>
    <!-- End div box -->
     <div class="groupbox">
       <g:render template="../templates/blank"/>
     </div>


    </div>
    <!-- End div main -->
    <div id="footer">
       <g:render template="../templates/footer"/>
    </div>
</div>
</body>

</html>